services:
  - type: web
    name: cashflow-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.20
