name: Deploy
on:
  push:
    branches: [ main ]

env:
  GOOGLE_CREDENTIALS_FILE: ${{ secrets.GOOGLE_CREDENTIALS_FILE }}
  API_KEY: ${{ secrets.API_KEY }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
  GOOGLE_SHEET_KEY: ${{ secrets.GOOGLE_SHEET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pytest pytest-mock
      - name: Run Tests
        run: |
          python3 -m pytest tests/ -v
