name: Deploy
on:
  push:
    branches: [ main ]

env:
  GOOGLE_CREDENTIALS_FILE: ${{ secrets.GOOGLE_CREDENTIALS_FILE }}
  API_KEY: ${{ secrets.API_KEY }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
  GOOGLE_SHEET_KEY: ${{ secrets.GOOGLE_SHEET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Application
        run: python app.py
